spring:
  
  security:
        user:
            name: user
            password: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micom
    username: root
    password: root

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

server:
  port: 8081  # 원하는 포트 번호로 설정